# Generated by Django 6.0.3 on 2026-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macronote', '0002_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('TRAVAIL', 'Travail'), ('LOISIRS', 'Loisirs'), ('COURSES', 'Courses'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10),
        ),
    ]
