# Generated by Django 6.0.3 on 2026-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macronote', '0003_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Normale'), ('2', 'Urgente ')], default='1', max_length=1),
        ),
    ]
